### ISSUE TITLE
Mise en place de QTest pour les tests unitaires

### ISSUE THREAD

**Issue by Energiiz** [speakproject/client#15]
Création des tests unitaires des fonctionnalités déjà existantes et des nouvelles.

**Comment by Weiko** [comment]
J'ai push un exemple de test. APIController est déjà inclut donc si on veut faire des tests il suffit de faire une méthode de cas et y instancier un objet APIController.
Liste des assertions possibles : http://doc.qt.io/qt-5/qtest.html#QBENCHMARK
QVERIFY_EXCEPTION_THROWN sera sans doute la plus utilisée si on fait les choses bien.
